# Pick a good base image for your language stack
# FROM node:16.10.0-alpine3.14

# set the app directory that your stack expects
# WORKDIR /usr/src/app

# copy in your source files
# COPY . .

# run any compilation steps your stack needs
# RUN npm install \
#   && npm run build

# port 8080 is set by default in your snake's vars.yaml
# EXPOSE 8080

# set the command to start your API server
# CMD ["node", "build/index.js"]